batch_size: 32
cpu_workers: 4
data_len: 150000
epochs: 20
fp16: false
lr: 5.0e-06
lr_scheduler: exp
max_len: 200
max_length: 150
model_name: HanBart-54kN
optimizer: AdamW
pretrained_model: beomi/kcbert-base
pretrained_tokenizer: ''
random_seed: 42
test_mode: false
tpu_cores: 0
train_data_path: ../nsmc/ratings_train.txt
val_data_path: ../nsmc/ratings_test.txt
